### ISSUE TITLE
Color picker for Contact Checker & Reply Checker Scripts

### ISSUE THREAD

**Issue by mindofbeholder** [mindofbeholder/SRToolkit-Issues#10]
Add a color picker to the options page so users can choose their own colors for these scripts.

**Comment by petieclark** [comment]
added html for color picker to options page. (now just need to make it work lol)

**Comment by mindofbeholder** [comment]
This was for customizing the colors in the contact checker and reply scripts. 

I created a new issue for the magic floating button. 

Closing this one as an unnecessary enhancement.
