### ISSUE TITLE
OpenHire MFB

### ISSUE THREAD

**Issue by petieclark** [mindofbeholder/SRToolkit-Issues#15]
ajax request to pull ATS URL id="OpenHire_Domain_ATS"

$('#OpenHire_Domain_ATS').value

**Comment by petieclark** [comment]
the open hire MFB opens the open admin sign in portal for a company instead of going to central admin THEN going to open admin

**Comment by mindofbeholder** [comment]
Published and pushed to un-stable distro

**Comment by mindofbeholder** [comment]
Added additional protections to detect garbage URLs and if a call fails and pushed to un-stable.
