### ISSUE TITLE
Touched case Idea

### ISSUE THREAD

**Issue by mindofbeholder** [mindofbeholder/SRToolkit-Issues#3]
Checkbox column to mark whether a case is touched or not

**Comment by mindofbeholder** [comment]
@silveramoon
What was the purpose of this idea?

**Comment by Silveramoon** [comment]
It is how I track cases that I have touched or if they are new and need
attention. It's a visual cue that I use.

**Comment by mindofbeholder** [comment]
Where would this button/toggle go on the page?

**Comment by Silveramoon** [comment]
Either as a right click or the button at the bottom, as long as there's an
option to mass click, I'm happy. :)

**Comment by mindofbeholder** [comment]
This issue was moved to mindofbeholder/SRToolkit#62
