### ISSUE TITLE
Salesforce Contact Option

### ISSUE THREAD

**Issue by Silveramoon** [mindofbeholder/SRToolkit-Issues#5]
I feel it would be more streamlined to move the Salesforce Contacts option to the first drill down box so it is faster while on calls.

**Comment by mindofbeholder** [comment]
What do you propose the new position be labeled?

**Comment by Silveramoon** [comment]
SF Contact List

**Comment by mindofbeholder** [comment]
That seems contextually confusing. I feel like if you didn't know what it's purpose was you might click it on the wrong page although that can be gotten around with proper user education.

I'll put it in place under a separator and see how that goes.
