### ISSUE TITLE
Salesforce Case Action

### ISSUE THREAD

**Issue by Silveramoon** [mindofbeholder/SRToolkit-Issues#7]
Is there any way to select/deselect the action marker in SalesForce en masse like the option we have for Onboarding check all teams? To be more specific the blue check marks and the green circles, not the check boxes to the far left.

![action checkmarks](https://cloud.githubusercontent.com/assets/27697239/25150431/e0acc848-244f-11e7-8707-e20dd58b152f.png)

**Comment by mindofbeholder** [comment]
This issue was moved to mindofbeholder/SRToolkit#61
